# Generated by Django 3.2 on 2021-04-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='User',
        ),
    ]
